version: '3.1'

services:
  webserver:
    image: caddy:2.4.6-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public:/public
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./.caddy:/root/.caddy

